<?php

declare(strict_types=1);

/**
 * This file is part of Daycry Queues.
 *
 * (c) Daycry <daycry9@proton.me>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Daycry\Jobs\Interfaces;

/**
 * Queue producer contract.
 * Implementations enqueue a job description object and return a string identifier.
 * The $data object SHOULD contain at minimum: job (string handler key) and payload (mixed). Optional fields:
 *  - queue: logical queue name
 *  - schedule: \DateTime for delayed execution
 *  - priority: backend-specific priority integer
 */
interface QueueInterface
{
    /**
     * Enqueue a job.
     *
     * @param object $data Job descriptor object (see interface docblock for expected properties)
     *
     * @return string Unique identifier generated by the backend.
     */
    public function enqueue(object $data): string;
}
